version: '3.5'
services:
  mono-graph:
    build: .
    container_name: mono-graph
    restart: unless-stopped
    tty: true
    network_mode: host
    user: 1000:1000
    command: pnpm dev
    volumes:
      - '../../:/app'
    ports:
      - '4200:4200'
      - '3333:3333'
    depends_on:
      - install-ui-libs

  install-ui-libs:
    build: .
    command: pnpm install
    user: 1000:1000
    volumes:
      - '../../:/app'
